
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'WLGLab-MusicStore'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'MusicStore'
    location: 'Australia East'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/pierzapin/dotnet-core-sample-templates/master/dotnet-core-music-windows/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/pierzapin/dotnet-core-sample-templates/master/dotnet-core-music-windows/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
